config/routes.rb
Rails.application.routes.draw do
  devise_for :bloggers
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles  #only: [:show, :index, :new , :create ,:edit, :update]
  get'signup' ,to: 'users#new'
  resources :users, except: [:new]
  resources :bloggers , only: [:show ,:index]
  resources :comments, only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blogger
  has_many :comments
  validates :title , presence: true ,length: {minimum: 6, maximum: 100}
  validates :description , presence: true , length: {minimum: 10 , maximum: 200}

end

app/models/blogger.rb
class Blogger < ApplicationRecord
  before_save {self.email=email.downcase}
  has_many :articles, dependent: :destroy 
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blogger
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email =email.downcase}
  has_many :articles
  validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController

def show
  @article=Article.find(params[:id])
end

def index
  @articles = Article.paginate(page: params[:page], per_page: 5)
end

def new
  @article= Article.new
end

def edit
  @article = Article.find(params[:id])
end

def create
  #render plain: params[:article]
  @article= Article.new(params.require(:article).permit(:title, :description))
  @article.user=User.first
  #render plain: @article
  #render plain: @article.inspect
    if @article.save   #redirect_to article_path(@article)
      redirect_to @article
        else
          render 'new'
    end
end

def update
  @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      #flash[:notice] = "Article was updated successfully."
      redirect_to @article
        else
          render 'edit'
        end
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy
  redirect_to articles_path 
end

end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
    #before_action :authenticate_blogger!
    #before_action :require_user, only:[:edit,:update]
    
    def index
      @bloggers= Blogger.paginate(page: params[:page], per_page: 5)
    end

    def show
      @blogger=Blogger.find(params[:id])
      @articles=@blogger.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
      @blogger=Blogger.find(params[:id])
    end

    def update
      @blogger=Blogger.find(params[:id])
        if @blogger.update(params.require(:blogger).permit(:email,:password))
          flash[:notice]="Your account updated successfully"
          redirect_to articles_path
          else
            render 'edit'
          end
    end

    def destroy
      @blogger=Blogger.find(params[:id])
      @blogger.destroy
      session[:user_id]=nil
      flash[:notice]="Account and all associated bloggers deleted!"
      redirect_to bloggers_path
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
  def new
    @comment=Comment.new
  end
  
  def create
    # byebug
    @comment=Comment.new(comment_params)
      if @comment.save
        flash[:notice]="Comment Successfully Added"
        #redirect_to post_path(@comment.post_id)
        redirect_back fallback_location: @article
      else
        flash.now[:alert]="Fill correct details"
            render 'new'
      end

  end
  
  def comment_params
    params.require(:comment).permit(:data,:article_id,:blogger_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end

  def show
    @user = User.find(params[:id])
    @articles= @user.articles.paginate(page: params[:page], per_page: 5)  
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @user= User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
          else
            render 'edit'
      end
  end

  def create
    @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
        redirect_to articles_path
          else
            render 'new'
          end
  end
    
    private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
          <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article%>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
              <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
            </div>
        </div>
         <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
         </div>
         <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 
 

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form' %>
</div> 

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Listing all articles</h1>
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>
    <%= render 'article' %>
     <div class="flickr_pagination mb-4">
       <%= will_paginate @articles, :container => false %>
     </div> 
</div> 

app/views/articles/new.html.erb
<h1>Create a new article</h1>
  <div id="page-content">
    <h1 class="text-center mt-4">Create a new article</h1>
      <%= render 'form' %>
      <%= link_to 'Return to articles listing', articles_path %> 
  </div> 

app/views/articles/show.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @article.title %></h2>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              by <%= @article.blogger.email if @article.blogger %>
              <%= link_to gravatar_for(@article.blogger), blogger_registration_path(@article.blogger) %>
            </div>
            <div class="card-body">
              <div class="card-text text-left"><%= simple_format(@article.description) %></div>
              </div>
              <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
              </div>
            </div>
                 <% if blogger_signed_in? && @article.blogger!=current_blogger %>
                   <%= form_with scope: :comment, url: comments_path, local: true do |f|%>
                    <div class="form-group row justify-content-center">
                      <div class="col-10">
                        <%= f.text_area :data,rows:3, class:"form-control shadow-sm bg-white rounded",placeholder:"Comment on Post" %>
                      </div>
                        <div class="form-group row">
                          <div class="col-10">
                            <%= f.number_field :article_id, id: :comment_article_id, class:"form-control", value: @article.id,type: :hidden %>
                          </div>   
                        </div>
                          <div class="form-group row">
                            <div class="col-10">
                              <%= f.number_field :blogger_id, id: :comment_blogger_id, class:"form-control", value: current_blogger.id,type: :hidden%>
                            </div>   
                          </div>
                    </div>
                      <div class="form-group row justify-content-center">
                        <%= f.submit "Add Comment", class:"btn btn-primary btn-lg" %>
                      </div>
                 <% end %>
                 <% end %>
                   <br/>
                     <h3><b>Comments:-</b></h3>
                       <% if @comments.count==0 %>
                         <p class="text-center">No Comments Yet</p>
                           <% else %> 
                             <% @comments.each do |comment| %>
                               <div class="card mt-4">
                                 <div class="card-header">
                                   by <%= comment.blogger.email.split("@")[0].capitalize %>
                                 </div>
                                   <div class="card-body">
                                     <%= comment.data %>
                                   </div>
                               </div>
                           <% end %>  
                       <% end %>  
          </div>
        </div>
      </div>
</div>   

app/views/bloggers/edit.html.erb
<div id="page-content">
  <div class="container mt-4"> 
    <div class="row justify-content-center">
      <div class="col-10">
        <%= render 'shared/errors',obj: @blogger  %>
        <%= form_with(model: @blogger, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "Enter Email" %>
                </div>
              </div>
              <div class="form-group row">
                <%= f.label :password, class: "col-2 col-form-label text-light" %>
                  <div class="col-10">
                    <%= f.password_field :description, rows:10, class: "form-control shadow rounded", placeholder: "Enter password" %>
                  </div>
              </div>
              <div class="form-group row justify-content-center">
                <%= f.submit "Update Account", class: "btn btn-outline-light btn-lg" %>
              </div>
            <% end %>
            </div>
            <div class="mb-3">
              <%= link_to '[ Cancel and return to article listing ]', articles_path %>
            </div>    
    </div>
  </div>
</div>
    

app/views/bloggers/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Bloggers</h1>
    <div class="flickr_pagination">
      <%= will_paginate @bloggers, :container => false %>
    </div>
    <div class="container">
      <% @bloggers.each do |blogger| %>
        <div class="row justify-content-md-center">
          <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-header font-italic">
                By <%= blogger.email.split("@")[0].capitalize %>
               </div>
               <div class="card-body">
                  <h5 class="card-title"><%= pluralize(blogger.articles.count,"article") %></h5>
                    <%= link_to "View Profile", blogger_path(blogger), class: "btn btn btn-outline-success" %>
                    <% if blogger_signed_in? && blogger==current_blogger %>
                    <%= link_to "Edit Profile", edit_blogger_path(current_blogger), class: "btn btn-outline-primary" %>
                    <% end %>    
                </div>
                <div class="card-footer text-muted">
                  <small>
                    Joined <%= time_ago_in_words(blogger.created_at) %> ago
                  </small>
                </div>
            </div>
          </div>
        </div>
        <% end %>
    </div>
    <div class="flickr_pagination mb-4">
      <%= will_paginate @bloggers, :container => false %>
    </div>
</div>

app/views/bloggers/show.html.erb
<div id="page-content">
  <h1 class="text-center mt-4"><%= @blogger.email.split("@")[0].capitalize %>'s Profile</h1>
    <h3 class="text-center mt-4">Articles</h3>
      <% if @blogger.articles.count==0 %>
       <h4 class="text-center mt-4"> No Articles Yet <h4>
         <% else %>    
           <div class="flickr_pagination mb-4">
             <%= will_paginate @articles, :container => false %>
           </div>
             <%= render 'articles/article' %>
              <div class="flickr_pagination mb-4">
                <%= will_paginate @articles, :container => false %>
              </div>
          <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy;My Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG" , root_path, class: "navbar-brand" , id: "logo"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Articles
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
                <%= link_to "View articles", articles_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
            </li>
            <li class="nav-item">
              <%= link_to 'sign_out' , destroy_blogger_session_path, class: "nav-link" ,method: :delete %>
            </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>
        
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Alphablog</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>
          <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
      <body>
        <body class="d-flex flex-column">
          <%= render 'layouts/navigation'%>
          <%= render 'layouts/messages'%>
            <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
                <%= yield %>
                <%= render 'layouts/footer'%>
        </body>
  </html>

app/views/pages/about.html.erb
<h1> Welcome To about Page  </h1>
    <%= link_to 'Articles list' , articles_path %> 
    <%= link_to 'home page' , root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Blog</h1>
       <hr class="my-4">
         <p>Welcome to Alpha Blog</p>
           <%= link_to "sign up ", new_blogger_registration_path , class: "btn btn-success btn-lg"%>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%>  from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user%>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :Username, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter Username" %>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
              <%= f.email_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
            </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
              <%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Enter your password" %>
            </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
        <% end %>
    </div>
      <div class="mb-3">
        <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
      </div>
  </div>
</div> 
 

app/views/users/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit your Profile</h1>
    <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
  <div class="container">
    <% @users.each do |user| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <%= link_to user.username, user %> 
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 150), user %>
              </h5>
                <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
                  <%= link_to "View profile", user, class: "btn btn-outline-success" %>
                  <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            </div>
            <div class="card-footer text-muted">
              <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
            </div>
          </div>
        </div>
  </div>
  <% end %>
</div>
<div class="flickr_pagination mb-5">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Sign Up For Alpha Blog</h1>
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div id="page-content">
  <%= gravatar_for @user, size: 200 %>
  <div class="text-center mt-4">
    <h3>  <%= @user.username%>
    </h3>
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
  <h3 class="text-center mt-4">Articles</h3>
    <div class="flickr_pagination">
      <%= will_paginate @articles, :container => false %>
    </div
    <%= render 'articles/article' %>
      <div class="flickr_pagination mb-5">
       <%= will_paginate @articles, :container => false %>
      </div>
</div>